imports:
    - { resource: 'admin/*' }

services:
    # default configuration for services in *this* file
    _defaults:
        public: false

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    harentius_blog.menu.menu_builder:
        class:  Harentius\BlogBundle\Menu\MenuBuilder
        arguments:
            - '@knp_menu.factory'
            - '@doctrine.orm.entity_manager'
            - '@harentius_blog.router.publication_url_generator'
            - '%harentius_blog.homepage.page_slug%'

    harentius_blog.menu.main:
        class: Knp\Menu\MenuItem
        factory: ['@harentius_blog.menu.menu_builder', 'createMainMenu']
        tags:
            - { name: knp_menu.menu, alias: main }

    harentius_blog.array_cache:
        class: Doctrine\Common\Cache\ArrayCache

    harentius_blog.twig.blog_extension:
        class: Harentius\BlogBundle\Twig\BlogExtension
        arguments:
            - '@twig.runtime.httpkernel'
            - ~
            - '@harentius_blog.rating'
            - '@harentius_blog.settings_provider'
            - '%harentius_blog.sidebar.cache_lifetime%'
            - '@harentius_blog.entity.translation'
            - '%harentius_blog.primary_locale%'
        tags:
            - { name: twig.extension }

    harentius_blog.twig.publication_url_generator_extension:
        class: Harentius\BlogBundle\Twig\PublicationUrlGeneratorExtension
        arguments:
            - '@harentius_blog.router.publication_url_generator'
        tags:
            - { name: twig.extension }

    harentius_blog.sidebar.tags:
        public: true
        class: Harentius\BlogBundle\Sidebar\Tags
        arguments:
            - '@harentius_blog.entity.tag_repository'
            - '%harentius_blog.sidebar.tags_limit%'
            - '%harentius_blog.sidebar.tag_sizes%'

    harentius_blog.sidebar.archive:
        class: Harentius\BlogBundle\Sidebar\Archive
        public: true
        arguments:
            - '@harentius_blog.entity.article_repository'

    harentius_blog.homepage:
        class: Harentius\BlogBundle\Homepage
        public: true
        arguments:
            - '@harentius_blog.entity.article_repository'
            - '@harentius_blog.entity.page_repository'
            - '%harentius_blog.homepage.feed.category%'
            - '%harentius_blog.homepage.page_slug%'

    harentius_blog.rating:
        class: Harentius\BlogBundle\Rating
        arguments:
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
            - '@harentius_blog.rating_cache'

    harentius_blog.views_counter:
        public: true
        class: Harentius\BlogBundle\ViewsCounter
        arguments:
            - '@session'
            - '@doctrine.orm.entity_manager'

    harentius_blog.assets.resolver:
        class: Harentius\BlogBundle\Assets\Resolver
        arguments:
             - '%kernel.root_dir%/../public'

    harentius_blog.assets.manager:
        class: Harentius\BlogBundle\Assets\Manager
        arguments:
            - '@harentius_blog.assets.resolver'

    harentius_blog.settings_provider:
        class: Harentius\BlogBundle\SettingsProvider
        arguments:
             - '@harentius_blog.entity.setting_repository'
             - '@harentius_blog.settings.cache'

    harentius_blog.event_listener.sitemap_listener:
        class: Harentius\BlogBundle\Sitemap\SitemapSubscriber
        arguments:
            - '@router'
            - '@harentius_blog.homepage'
            - '@harentius_blog.entity.article_repository'
            - '@harentius_blog.entity.page_repository'
            - '@harentius_blog.entity.category_repository'
            - '%harentius_blog.homepage.page_slug%'
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    harentius_blog.router.category_slug_provider:
          class: Harentius\BlogBundle\Router\CategorySlugProvider
          arguments:
              - '@harentius_blog.entity.category_repository'
              - '@harentius_blog.router.category_slug_provider_cache'

    harentius_blog.router.route_provider:
          class: Harentius\BlogBundle\Router\RouteProvider
          arguments:
              - '@harentius_blog.router.category_slug_provider'

    harentius_blog.feed:
        class: Harentius\BlogBundle\Feed
        arguments:
            - '@harentius_blog.entity.article_repository'
            - '@eko_feed.feed.manager'
            - '@harentius_blog.controller.feed_cache'

    harentius_blog.statistics:
        class: Harentius\BlogBundle\Statistics
        arguments:
            - '@harentius_blog.statistics_cache'
            - '%harentius_blog.cache.statistics_cache_lifetime%'
            - '@harentius_blog.entity.article_repository'

    harentius_blog.image_optimizer:
        class: Harentius\BlogBundle\ImageOptimizer
        arguments:
            - '@liip_imagine.cache.manager'
            - '@liip_imagine.filter.manager'
            - '@liip_imagine.data.manager'
            - '@harentius_blog.assets.resolver'
            - '%harentius_blog.articles.image_previews_base_uri%'

    harentius_blog.event_listener.admin_user_listener:
        class: Harentius\BlogBundle\EventListener\AdminUserListener
        arguments:
            - '@security.password_encoder'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    harentius_blog.router.publication_url_generator:
        class: Harentius\BlogBundle\Router\PublicationUrlGenerator
        arguments:
            - '@request_stack'
            - '@router'
